apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appointment-service
  template:
    metadata:
      labels:
        app: appointment-serice
    spec:
      containers:
      - name: appointment-service
        image: imashasithmini/appointment-service:latest
        ports:
        - containerPort: 5001
        env:
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: appointment-service-config
              key: ENVIRONMENT
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: appointment-service-config
              key: DATABASE_URL
        - name: SERVICE_NAME
          valueFrom:
            configMapKeyRef:
              name: appointment-service-config
              key: SERVICE_NAME
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: appointment-service-secret
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: appointment-service-secret
              key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: appointment-service
spec:
  selector:
    app: appointment-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5001
  type: LoadBalancer
