apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-service-deployment
  labels:
    app: appointment-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appointment-service
  template:
    metadata:
      labels:
        app: appointment-service
    spec:
      containers:
      - name: appointment-service
        image: imashasithmini/appointment-service:latest
        ports:
        - containerPort: 5001
