apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-record-deployment
  labels:
    app: patient-record-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: patient-record-service
  template:
    metadata:
      labels:
        app: patient-record-service
    spec:
      containers:
      - name: patient-record-service
        image: imashasithmini/patient-record-service:latest
        ports:
        - containerPort: 5000
